<?php
require_once 'admin/db.php';
header('Content-Type: text/plain');

function map_crime_type($tipo)
{
    $tipo = strtoupper(trim($tipo));
    $mappings = [
        'PATRIMONIO (DELITO)' => 'CONTRA EL PATRIMONIO',
        'LIBERTAD (DELITO)' => 'CONTRA LA LIBERTAD',
        'VIDA, EL CUERPO Y LA SALUD (DELITO)' => 'CONTRA LA VIDA EL CUERPO Y LA SALUD',
        'VIDA EL CUERPO Y LA SALUD (DELITO)' => 'CONTRA LA VIDA EL CUERPO Y LA SALUD',
        'SEGURIDAD PUBLICA (DELITO)' => 'CONTRA LA SEGURIDAD PUBLICA',
        'FAMILIA (DELITO)' => 'CONTRA LA FAMILIA',
        'ADMINISTRACION PUBLICA (DELITO)' => 'CONTRA LA ADMINISTRACION PUBLICA',
        'FE PUBLICA (DELITO)' => 'CONTRA LA FE PUBLICA',
        'TRANQUILIDAD PUBLICA (DELITO)' => 'CONTRA LA TRANQUILIDAD PUBLICA',
        'AMBIENTALES' => 'CONTRA EL MEDIO AMBIENTE',
        'HONOR (DELITO)' => 'CONTRA EL HONOR',
        'DERECHOS INTELECTUALES (DELITO)' => 'CONTRA LOS DERECHOS INTELECTUALES',
        'ORDEN FINANCIERO Y MONETARIO (DELITO)' => 'CONTRA EL ORDEN FINANCIERO Y MONETARIO',
        'TRIBUTARIOS (DELITO)' => 'DELITOS TRIBUTARIOS',
        'PATRIMONIO CULTURAL (DELITO)' => 'CONTRA EL PATRIMONIO CULTURAL',
        'CONFIANZA Y LA BUENA FE EN LOS NEGOCIOS (DELITO)' => 'CONTRA LA CONFIANZA Y LA BUENA FE EN LOS NEGOCIOS',
        'ORDEN ECONOMICO (DELITO)' => 'CONTRA EL ORDEN ECONOMICO',
        'ESTADO Y LA DEFENSA NACIONAL (DELITO)' => 'CONTRA EL ESTADO Y LA DEFENSA NACIONAL',
        'VOLUNTAD POPULAR (DELITO)' => 'CONTRA LA VOLUNTAD POPULAR',
        'HUMANIDAD (DELITO)' => 'CONTRA LA HUMANIDAD',
        'PODERES DEL ESTADO Y EL ORDEN CONSTITUCIONAL (DELITO)' => 'CONTRA LOS PODERES DEL ESTADO Y EL ORDEN CONSTITUCIONAL'
    ];

    foreach ($mappings as $key => $val) {
        if (strpos($tipo, $key) !== false || $tipo == $key) {
            return $val;
        }
    }
    return $tipo;
}

echo "Iniciando reparación de categorías...\n";

$mappings = [
    'PATRIMONIO (DELITO)' => 'CONTRA EL PATRIMONIO',
    'LIBERTAD (DELITO)' => 'CONTRA LA LIBERTAD',
    'VIDA, EL CUERPO Y LA SALUD (DELITO)' => 'CONTRA LA VIDA EL CUERPO Y LA SALUD',
    'VIDA EL CUERPO Y LA SALUD (DELITO)' => 'CONTRA LA VIDA EL CUERPO Y LA SALUD',
    'SEGURIDAD PUBLICA (DELITO)' => 'CONTRA LA SEGURIDAD PUBLICA',
    'FAMILIA (DELITO)' => 'CONTRA LA FAMILIA',
    'ADMINISTRACION PUBLICA (DELITO)' => 'CONTRA LA ADMINISTRACION PUBLICA',
    'FE PUBLICA (DELITO)' => 'CONTRA LA FE PUBLICA',
    'TRANQUILIDAD PUBLICA (DELITO)' => 'CONTRA LA TRANQUILIDAD PUBLICA',
    'AMBIENTALES' => 'CONTRA EL MEDIO AMBIENTE',
    'HONOR (DELITO)' => 'CONTRA EL HONOR',
    'DERECHOS INTELECTUALES (DELITO)' => 'CONTRA LOS DERECHOS INTELECTUALES',
    'ORDEN FINANCIERO Y MONETARIO (DELITO)' => 'CONTRA EL ORDEN FINANCIERO Y MONETARIO',
    'TRIBUTARIOS (DELITO)' => 'DELITOS TRIBUTARIOS',
    'PATRIMONIO CULTURAL (DELITO)' => 'CONTRA EL PATRIMONIO CULTURAL',
    'CONFIANZA Y LA BUENA FE EN LOS NEGOCIOS (DELITO)' => 'CONTRA LA CONFIANZA Y LA BUENA FE EN LOS NEGOCIOS',
    'ORDEN ECONOMICO (DELITO)' => 'CONTRA EL ORDEN ECONOMICO',
    'ESTADO Y LA DEFENSA NACIONAL (DELITO)' => 'CONTRA EL ESTADO Y LA DEFENSA NACIONAL',
    'VOLUNTAD POPULAR (DELITO)' => 'CONTRA LA VOLUNTAD POPULAR',
    'HUMANIDAD (DELITO)' => 'CONTRA LA HUMANIDAD',
    'PODERES DEL ESTADO Y EL ORDEN CONSTITUCIONAL (DELITO)' => 'CONTRA LOS PODERES DEL ESTADO Y EL ORDEN CONSTITUCIONAL'
];

foreach ($mappings as $old => $new) {
    $stmt = $pdo->prepare("UPDATE sidpol_hechos SET tipo_delito = ? WHERE tipo_delito LIKE ?");
    $stmt->execute([$new, "%$old%"]);
    echo "Actualizado: $old -> $new (" . $stmt->rowCount() . " filas)\n";
}

echo "\nReparación finalizada.";
